

##  ˝æ›ø‚≈‰÷√
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.114:3306/test
    username: root
    password: root

  ## «∞∂Œ“≥√Ê≈‰÷√
  thymeleaf:
    prefix: classpath:/pages/
    cache: false
  resources:
    static-locations: classpath:/static/

## mybatis ≈‰÷√
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.loong.blog.model
